title: Javier Sigüenza - Actividad UNIR
description: Blog creado para la Actividad 1 de Desarrollo de Aplicaciones en Red

# Build settings
theme: minima

# Para que Jekyll sepa dónde buscar la página principal
# Este código le indica que use 'index.html' con el layout 'home'
collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "home"